/*
Name: Daniel Araujo
Date: 21 Aug 18
Title: Connect Four GUI
Purpose: to create a functioning Connect Four GUI
*/

import javax.swing.*; //imports classes required for the GUI elements

public class ConnectFourGUI extends javax.swing.JFrame {
    
    ConnectFourEvent connectFour = new ConnectFourEvent(this); //joins the ConnectFourGUI and ConnectFourEvent program so they work together
    JButton[][] btnGameBoard = new JButton [6][7]; //declares a 2-d button array that is 6 by 7 - represents game board
    ImageIcon empty = new javax.swing.ImageIcon(getClass().getResource("/imageresources/Empty Piece.jpg")); //declares ImageIcon variable empty and stores the Empty Piece.jpg icon - represents an empty Game Board square
    
    /**
     * Creates new form ConnectFourGUI
     */
    public ConnectFourGUI() {
        initComponents();
        
        int intName = 0; //declares integer intName variable - used to store the name of the button
        
        for (int x=0; x < 6; x++) { //runs through the rows of the btnGameBoard array
            for (int y = 0; y < 7; y++) { //runs through the columns of the btnGameBoard array
                intName++; //increases the value of intName by 1 - used to number to buttons in order
                btnGameBoard[x][y] = new JButton(); //declares a JButton at the specific indexes
                pnlGameBoard.add(btnGameBoard[x][y]); //adds JButton at index [x][y] to pnlGameBoard
                btnGameBoard[x][y].addActionListener(connectFour); //adds action listener to the button
                btnGameBoard[x][y].setActionCommand(Integer.toString(intName)); //sets the action command of the button to intName - converts to string
                btnGameBoard[x][y].setIcon(empty); //sets the icon of the button to the image stored as the variable empty
                btnGameBoard[x][y].setContentAreaFilled(false); //sets the content area as false so only icon of the button shows
            }
        }
        btnPlay.addActionListener(connectFour); //makes the ConnectFourEvent file ready to handle the Play (btnPlay) button being clicked
        btnMainMenu1.addActionListener(connectFour); //makes the ConnectFourEvent file ready to handle the Main Menu (btnMainMenu1) button being clicked
        btnExit.addActionListener(connectFour); //makes the ConnectFourEvent file ready to handle the Exit (btnExit) button being clicked
        btnExit3.addActionListener(connectFour); //makes the ConnectFourEvent file ready to handle the Exit (btnExit3) button being clicked
        btnPlayAgain.addActionListener(connectFour); //makes the ConnectFourEvent file ready to handle the Play Again (btnPlayAgain) button being clicked
        btnNewGame.addActionListener(connectFour); //makes the ConnectFourEvent file ready to handle the New Game (btnNewGame) button being clicked
        
        pnlMainMenu.setVisible(true); //sets the pnlMainMenu panel visible
        splGame.setVisible(false); //sets the splGame panel as not visible
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainMenu = new javax.swing.JPanel();
        lblMainTitle = new javax.swing.JLabel();
        lblInstructions = new javax.swing.JLabel();
        lblGameName = new javax.swing.JLabel();
        txtGameName = new javax.swing.JTextField();
        lblPlayer1 = new javax.swing.JLabel();
        txtPlayer1 = new javax.swing.JTextField();
        lblPlayer2 = new javax.swing.JLabel();
        txtPlayer2 = new javax.swing.JTextField();
        btnPlay = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        splGame = new javax.swing.JSplitPane();
        pnlGameBoard = new javax.swing.JPanel();
        pnlGameBottom = new javax.swing.JPanel();
        btnPlayAgain = new javax.swing.JButton();
        btnNewGame = new javax.swing.JButton();
        txtTurn = new javax.swing.JTextField();
        scrScore = new javax.swing.JScrollPane();
        txtScore = new javax.swing.JTextArea();
        btnExit3 = new javax.swing.JButton();
        btnMainMenu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connect Four");
        setResizable(false);

        pnlMainMenu.setForeground(new java.awt.Color(153, 255, 255));

        lblMainTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        lblMainTitle.setForeground(new java.awt.Color(204, 0, 0));
        lblMainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainTitle.setText("Connect Four");

        lblInstructions.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lblInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions.setText("<html>The goal of Connect Four is to make 4 in a row of your own colored discs before your opponent does!</html>");

        lblGameName.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lblGameName.setText("Game Name:");

        txtGameName.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N

        lblPlayer1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lblPlayer1.setText("Player 1's Name:");

        txtPlayer1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N

        lblPlayer2.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lblPlayer2.setText("Player 2's Name:");

        txtPlayer2.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N

        btnPlay.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btnPlay.setText("Play");

        btnExit.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btnExit.setText("Exit");

        javax.swing.GroupLayout pnlMainMenuLayout = new javax.swing.GroupLayout(pnlMainMenu);
        pnlMainMenu.setLayout(pnlMainMenuLayout);
        pnlMainMenuLayout.setHorizontalGroup(
            pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainMenuLayout.createSequentialGroup()
                .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainMenuLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainMenuLayout.createSequentialGroup()
                                .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPlayer1)
                                    .addComponent(lblPlayer2)
                                    .addComponent(lblGameName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainMenuLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGameName)
                                    .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlMainMenuLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainMenuLayout.createSequentialGroup()
                .addGap(0, 227, Short.MAX_VALUE)
                .addComponent(lblInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        pnlMainMenuLayout.setVerticalGroup(
            pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainMenuLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblMainTitle)
                .addGap(27, 27, 27)
                .addComponent(lblInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMainMenuLayout.createSequentialGroup()
                        .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGameName)
                            .addComponent(txtGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(lblPlayer1))
                    .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPlayer2)
                    .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnPlay)
                .addGap(76, 76, 76)
                .addComponent(btnExit)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        splGame.setDividerLocation(600);
        splGame.setDividerSize(0);
        splGame.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splGame.setEnabled(false);

        pnlGameBoard.setLayout(new java.awt.GridLayout(6, 7, -28, 0));
        splGame.setLeftComponent(pnlGameBoard);

        btnPlayAgain.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        btnPlayAgain.setText("Play Again");

        btnNewGame.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        btnNewGame.setText("New Game");

        txtTurn.setEditable(false);
        txtTurn.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        txtTurn.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        scrScore.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        txtScore.setEditable(false);
        txtScore.setColumns(20);
        txtScore.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        txtScore.setRows(5);
        scrScore.setViewportView(txtScore);

        btnExit3.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        btnExit3.setText("Exit");

        btnMainMenu1.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        btnMainMenu1.setText("Main Menu");

        javax.swing.GroupLayout pnlGameBottomLayout = new javax.swing.GroupLayout(pnlGameBottom);
        pnlGameBottom.setLayout(pnlGameBottomLayout);
        pnlGameBottomLayout.setHorizontalGroup(
            pnlGameBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGameBottomLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pnlGameBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGameBottomLayout.createSequentialGroup()
                        .addGroup(pnlGameBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNewGame)
                            .addComponent(btnPlayAgain))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(txtTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(pnlGameBottomLayout.createSequentialGroup()
                        .addComponent(btnMainMenu1)
                        .addGap(46, 46, 46)
                        .addComponent(btnExit3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(scrScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnlGameBottomLayout.setVerticalGroup(
            pnlGameBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameBottomLayout.createSequentialGroup()
                .addGroup(pnlGameBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGameBottomLayout.createSequentialGroup()
                        .addGroup(pnlGameBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGameBottomLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(txtTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlGameBottomLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnPlayAgain)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNewGame)))
                        .addGroup(pnlGameBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGameBottomLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnExit3))
                            .addGroup(pnlGameBottomLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMainMenu1))))
                    .addComponent(scrScore, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        splGame.setBottomComponent(pnlGameBottom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splGame)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splGame, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnectFourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnectFourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnectFourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnectFourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnectFourGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit3;
    private javax.swing.JButton btnMainMenu1;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JLabel lblGameName;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JPanel pnlGameBoard;
    private javax.swing.JPanel pnlGameBottom;
    public javax.swing.JPanel pnlMainMenu;
    private javax.swing.JScrollPane scrScore;
    public javax.swing.JSplitPane splGame;
    public javax.swing.JTextField txtGameName;
    public javax.swing.JTextField txtPlayer1;
    public javax.swing.JTextField txtPlayer2;
    public javax.swing.JTextArea txtScore;
    public javax.swing.JTextField txtTurn;
    // End of variables declaration//GEN-END:variables
}
